//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Query.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Employee_ID { get; set; }
        public string Employee_Name { get; set; }
        public int Department { get; set; }
        public int Location { get; set; }
        public int Position_Type { get; set; }
    
        public virtual Department Department1 { get; set; }
        public virtual Location Location1 { get; set; }
        public virtual Position_Type Position_Type1 { get; set; }
    }
}
