//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Query.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_Type
    {
        public Request_Type()
        {
            this.Requests = new HashSet<Request>();
        }
    
        public int Request_Type_ID { get; set; }
        public string Request_Type_Name { get; set; }
    
        public virtual ICollection<Request> Requests { get; set; }
    }
}
